### ISSUE TITLE
Support for generic bundle notifications

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1038]
**Story**: as a user I would like to subscribe and be notified of generic ~~bucket bundle version~~ blue box events such as: create, update, and delete of files, bundles and collection.

**Requirements:**

- [ ] Users shall be able to limit subscription to a specific replica
- [ ] Users shall be able to subscribe to creation, update, or deletion events
- [ ] Users shall be able to create, modify, and delete subscriptions.
- [ ] Users shall be able to retrieve event history by date range.
- [ ] Users shall be able to retrieve the current collection, file, and bundle state of the replica.

- [ ] Must define the format for the each event.
- [ ] Must be able to replay events

**Definition of Done:**
Un/Subscribe and to generic events. Receive notification for subscribed events. Stop receiving notification for unsubscribed events. 
 
[Edits: 
1) This is about bundle versions 
2) Bundle versions are immutable; there is no update 
3) The notifications are performed at the level of the REST API, not at storage or bucket level

Hannes]

**Comment by Bento007** [comment]
How will users use the information from the notification?
How will users download the metadata?
Will we still need a manifest?
Will we still need any kind of indexing?
How will we track the current state of the replica?
How will we allow users to replay notifications?

**Comment by kozbo** [comment]
@xbrianh to draft up RFC
