### ISSUE TITLE
metadata caching

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1859]
## User story
As a developer building an index outside of DSS, I need to access every metadata file in the DSS whenever I rebuild my index. I rebuild and update my index frequently, so I need metadata access to be quick and economical.

As an operator of the DSS, I need a way to manage what files should remain in the DSS managed checkout bucket, to prevent frequently accessed files from leaving a low latency storage tier.

## Definition of done
* provide a configurable way of managing what files are not removed from checkout.
* metadate files are never removed from the dss managed checkout bucket.

# developer notes
* https://docs.google.com/document/d/1PQBO5qYUVJFAXFNaMdgxq8j0y-OI_EF2b15I6fvEYjo/edit#heading=h.9zi1h0926hiz

* modify checkout to mark special files as do not removed
  * use tags for aws
  * use storage type for GCS
* modify checkout bucket lifecycle policies for AWS and GCS to keep special files.

**Comment by amarjandu** [comment]
## Tasks

- [ ] Checkout AWS / GCP Process 
(Modifications to BlobStore) keyword args to put requests
- [ ] Terra-form Tagging
- [ ] Config File for Checkout Comparison 
Specified under Design Details 
- [ ] Checkout for DSS vs User
User checkout buckets should not have tag modifications

**Comment by amarjandu** [comment]
# Notes

### Pre-Testing
Overall goal for the RFC is to improve performance for services, Matt W // Andrey may have specific matrix tests that we can look at for seeing performance gains brought by the changes.

**Comment by amarjandu** [comment]
#Notes

### gotchas
Multi-file uploads are not allowed to use tagging to delete objects from the cache, im not sure if this will be an issue as we are planning to cache small files, not large ones.


### In-progress
waiting for PR to be pulled for s3 tagging to be permitted within the blobstore, this allows the `s3copyclient` to use copy_object and use tagging https://github.com/chanzuckerberg/cloud-blobstore/pull/25

### TODO

inspect gsCopyClient and see if there needs to be a modification to change the object type that is copied over. 

Verify `s3copyclient` for metadata copy, and also overload that function, this is waiting on the blobstore request.

implement changes to GS object type on checkout.
