### ISSUE TITLE
Scale PUT /bundle to support ~10^6 files (PATCH /bundle)

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1901]
- [x] Implement paging for GET /bundle
- [x] Support bundle agglomeration via PATCH
- [ ] Mark intermediate bundles as non-indexable

connects to #1891
