### ISSUE TITLE
Create Security.txt file for each Repo

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1936]

**Comment by DailyDreaming** [comment]
Tracking this here.  Needs a clearer definition of which repos need this file.

First "x" means I created a PR for that repo.  Second "x" means it's merged:
- [x][] lira
- [x][] matrix-service
- [x][] skylab
- [x][] query-service
- [x][] upload-service
- [x][x] dcp-cli
- [x][x] datastore
- [x][x] dcp
- [x][x] fusillade
- [x][x] dcp-diag
- [x][x] data-portal
- [x][x] data-browser

(needed?)
- [][] ingest-validator 
- [][] metadata-schema 
- [][] pipeline-tools 
- [][] ingest-kube-deployment 
- [][] sctools
- [][] ingest-archiver
- [][] metadata-api
- [][] secondary-analysis-deploy
- [][] data-portal-content
- [][] dcp-lib
- [][] ingest-core
- [][] metadata-schema-publisher
- [][] unity
- [][] ingest-file-archiver
- [][] ingest-broker
- [][] dcp-community

Private (unnecessary?)
- [][] allspark
- [][] dcp-infra
- [][] kharon
