### ISSUE TITLE
Resource Tagging

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#1997]
- [x] Establish tags/labels on resources
- [x] turn on tags to build report in cost explorer
- [x] write Draft RFC for Tech arch meeting (3/5/2019) 
- [ ] modify on-boarding docs for how to tag properly ( complete after RFC?)

Resolves #1980

**Comment by amarjandu** [comment]
## Notes 4/5/19 : 3:28 PM

### Complete
added changes to `infra` deployment in [2010](https://github.com/HumanCellAtlas/data-store/pull/2010) 
update resources with tagging

### In Progress
NA

### TODO
see changes in Cost Explorer, build example to show

### Awaiting 
Awaiting information to show up in Cost Explorer (may take a few days)

**Comment by xbrianh** [comment]
It appears resource tagging is causing conflicts in CI/CD, since the tags will always need to be updated.

Is it possible to:
 - Only update resource tagging when there are other changes. Otherwise tags will need to be updated every time a new users executes `make deploy-infra`.
 - Ignore resource tagging changes in CI/CD scripting. Otherwise we won't be able to detect infra changes from our build scripting.

**Comment by amarjandu** [comment]
## Notes 4/11/19 : 11:39 AM
Owner was changed to `dss-team@data.humancellatlas.org`
updates to enviornment variables + build scripts
updated resources within {dev,ntegration,staging}
### Complete


### In Progress

### TODO

### Awaiting
