### ISSUE TITLE
Remove the DSS Elasticsearch service

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2215]
- [x] Create JMESPath filterable bundle event notifications
- [ ] Create JMESPath filterable bundle enumeration endpoint
- [ ] Define SLO: performance characteristics for enumeration endpoints
- [ ] Ensure enumeration endpoints satisfy the needs of downstream content-discovery services such as the [query-service](https://github.com/HumanCellAtlas/query-service) and the [data-browser]().
- [ ] Announce the depreciation of the DSS Elasticsearch service
- [ ] Remove the DSS Elasticsearch service

**Comment by kozbo** [comment]
We have an epic for this
