### ISSUE TITLE
Log Management, analytics, eventing

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#532]
Basic monitoring and metric contributions to central dashboard from logging data, availability . @sampierson  I hear you may have some opinions on what you'd like to see. 

As an admin I want to be able to monitor activity and create statistics from patterns. I want to receive alerts for important events.

**Minimum implementation** would include a way to query the logs potentially using off the shelf log analytic programs. The alerts can be hard coded but should be programmatically configured in the future. 

### Features
- Analytics - searching logs.
- Alerting - email alerts.
- Dashboarding - metrics, from log data.

### Resources
any libraries, or tools we should consider
- pingdom

#### Milestone 1: Groundwork, spec collection
- [x] #595 Complete log management spec
- [x] Determine what to do with GCP Audit logs
- [x] Create a test application emitting logs in the new pattern
- [x] Clarify logging policies (what PII do we need to be mindful of, log retention), ~~meet with Counsel if necessary~~ speak with David B. from Broad
- [x] Identify which applications need to be migrated to new logging strategy, set up a checklist on what needs to be migrated

#### Milestone 2: MVP: Audit events and first app logs collected
- [x] Configure CloudTrail to send audit logs the the correct log groups/streams
- [x] Funnel Lambda to correct log groups/streams
- [ ] ~~Funnel any EC2 logs to correct log groups/streams~~\*
- [ ] ~~Funnel any CloudCompute node logs to the right log groups/streams~~\*
- [x] Write a service for export GCP application logs to CloudWatch. This service should work with application logs, audit logs, and data access logs
- [x] Configure and deploy instances of the GCP log exporter to send sample application, data access, and audit logs to the correct log groups/streams
- [x] Check that there's a strategy and/or alerts so that we don't run out of space on EC2 and CloudCompute nodes
- [x] Provide guidelines for logging out of docker containers

\* We currently aren't using these services.

#### Milestone 3: Demo-able monitoring and alerting
- [x] Demonstrate some examples in CloudWatch Analytics
- [x] Set up a base set of alerts CloudWatch Alerts
- [x] Set up an ElasticSearch cluster
- [x] Set up Kibana or Greylog
- [x] Set up a base set of plots on the CloudWatch metrics dashboard or Kibana
- [x] Put alert configuration under source control (?)

#### Milestone 3.5: Production readiness
- [x] Manage load on the ELK stack (retire old indices, autoscale, alert)
- [x] Automagically subscribe new log groups to the ELK exporter

#### Milestone 4: Migration
- [x] Define a migration strategy
- [x] Design log requirements for audit queries (e.g. including bundle ID in all bundle lifecycle logs)
- [x] Support groups migrating applications
- [x] Ensure alerting is in place for new applications
- [x] Ensure that we anonymize identities where necessary
- [x] Ensure that we expire logs where necessary

**Comment by ttung** [comment]
also, It'll be pretty valuable if our logging all landed in one cloud provider.

**Comment by sampierson** [comment]
I do not have opinions, other than that I think this is a good idea.

**Comment by ttung** [comment]
Specs from a zillion years ago https://docs.google.com/document/d/15RUEodhwS8wtgkIpoJ_6uI9eCErzAw2YXzY6MwwUcG4/edit

**Comment by Bento007** [comment]
connects to #595 Complete log management spec

**Comment by kozbo** [comment]
Sprint 12 - create updated RFC

**Comment by mweiden** [comment]
Incremental update: here is a sample project I wrote demonstrating sending application logs to CloudWatch logs from java and python apps https://github.com/mweiden/hca-logging-test
