### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#576]
Epic : Follow up on Auth spec to implement auth across boxes
- [x] #635 Auth: Investigate SAM
- [x] #636 Auth: prototype using OpenID
- [x] #893 Conduct integration session with purple box
- [ ] #1488 Auth: Example App
- [ ] Integrate with other boxes

**Comment by Bento007** [comment]
WIP document https://docs.google.com/document/d/1qD4bgnO684GtcLBErxYNZ5gvMaQPF8DsIdUBua5ZDBs/edit#heading=h.x01v6l5tv57z

**Comment by kozbo** [comment]
creating reference implementation of the Auth strategy in the blue box
Andrey to break down into sub-tasks

**Comment by kozbo** [comment]
@Bento007 can you update this epic? It seems to be a hybrid of AuthN and AuthZ, and has overlap with some of your other work.

**Comment by Bento007** [comment]
replaced by https://github.com/HumanCellAtlas/fusillade/issues/129
