### ISSUE TITLE
Build example queries for all use cases

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#577]
First story is #521

**Comment by kozbo** [comment]
Blocked waiting for V4 to drop

**Comment by caaespin** [comment]
Basic indexer prototype to create additional transformative indexes that can better answer various queries. 

As a blue box user, I want to use simple ElasticSearch queries and aggregations to answer different questions, as well as to perform faceted searches. 

**Minimum implementation**  would include a Base Indexer class that can be used as the basis for new indexing implementations (e.g. Donor indexer, assay indexer, etc.). It would also include at least 2/3 different Indexer subclasses to create a file oriented index and some other 1 or 2 TBD index. 

#### Features
* Base indexer class
* Deployed through AWS serverless technologies

#### Resources
* Chalice framework
* HCA CLI

#### TASKS
##### Milestone 1
- [ ] Refactor the current dss-azul-indexer, including creating a baseclass so that it is easier to extend from it and write custom indexes.
- [ ] Create a couple different new types of indexers that can better answer queries from the query spreadsheet. 
- [ ] Create a simplified mechanism to deploy the indexers to AWS
- [ ] Create a simplified mechanism to deploy a testing environment on localhost
- [ ] Create a testing framework
