### ISSUE TITLE
Admin Delete

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#596]
Administrator should be able to delete a bundle

## Short-term requirements
- [ ] The indexed metadata is replaced with a tombstone.
- [ ] In storage, a tombstone is added.
- [ ] Querying the manifest endpoint returns a tombstone as well.
- [ ] The reindexer converts blobstore tombstones into index tombstones

## In the future
- [ ] A mechanism to determine what downstream analyses are derived from this data
- [ ] CLI support for admin delete

## Nice to have
- [ ] Data is deleted from the checkout directory, helpful text file left behind.

**Comment by kozbo** [comment]
The Steering committee discussed the implementation of this: 
"The conclusion was that the scheme you describe — making the data unavailable nearly immediately, with actual deletion delayed — should be perfectly fine, and we get why it’s preferable from a technical perspective.

The only additional requirement brought up was keeping a record of which data files/bundles have been deleted in this way, but from Andrey it seems like the logging functionality should satisfy this."

**Comment by kozbo** [comment]
discussion doc here: https://docs.google.com/document/d/1PZI2I2-fgka110K7IlkVcf0CJgc8W6LhyFHQNoh6XV0/edit#heading=h.jksxojlpa1fd

**Comment by mweiden** [comment]
Base-level requirements fulfilled here.

**Comment by mweiden** [comment]
CLI issue here https://github.com/HumanCellAtlas/dcp-cli/issues/80
