### ISSUE TITLE
Alpha production storage of early data

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#999]
Verify that ingestion of first large datasets complete properly
- [x] Data files are in s3 storage and can be served from the DSS API
- [x] Files are not corrupted
- [x] Metadata passed validation
- [x] Indexed documents are correct

Work with @sampierson on ingestion side

**Comment by kozbo** [comment]
The conditions for this Epic have been met via the Preview release.
